app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
# from sqlalchemy.sql import func

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique = True, index = True)
    password_hash = db.Column(db.String(255))


    lines = db.relationship('Line', backref='user', lazy='dynamic')
    comments = db.relationship('Comment', backref='user', lazy='dynamic')
    # pitches = db.relationship('Pitch', backref='user', lazy='dynamic')
    # groups = db.relationship('Group', backref='user', lazy='dynamic')


    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self,password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)


    def __repr__(self):
        return f'User {self.username}'

class Group(db.Model):
    __tablename__ = 'groups'
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(255))
    lines = db.relationship('Line', backref='group', lazy='dynamic')

    def save_group(self):

        db.session.add(self)
        db.session.commit()
    
    @classmethod
    def get_groups(cls):

         groups = Group.query.all()

         return groups

class Line(db.Model):
    __tablename__ = 'lines'
    id = db.Column(db.Integer, primary_key = True)
    line_content = db.Column(db.String(200))
    group_id = db.Column(db.Integer, db.ForeignKey("groups.id") )
    user_id = db.Column(db.Integer, db.ForeignKey("users.id") )
    comments = db.relationship('Comment', backref='line', lazy='dynamic')

    def save_line(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_lines(cls,group_id):

        lines = Line.query.order_by(Line.id.desc()).filter_by(group_id=group_id).all()

        return lines

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer,primary_key = True)
    comment_content =db.Column(db.String)
    line_id =db.Column(db.Integer,db.ForeignKey('lines.id'))
    user_id =db.Column(db.Integer,db.ForeignKey('users.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,line_id):

        comments = Comment.query.filter_by(line_id=line_id).all()

        return comments

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class GroupForm(FlaskForm):
    '''
    Class to create a wtf form for creating a pitch
    '''
    name =  StringField('Category Name', validators=[Required()])
    submit = SubmitField('Create')

class LineForm(FlaskForm):
    '''
    Class to create a wtf form for creating a pitch
    '''
    line_content =  StringField('One Minute Pitch', validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    '''
    Class to create a wtf form for creating a feedback on a pitch
    '''
    comment_content =  TextAreaField('Comment', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

# Instances of flask extensions
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()
mail = Mail()

def create_app(config_name):
    '''
    Function that takes configuration setting key as an argument
    
    Args:
        config_name : name of the configuration to be used
    '''

    # Initialising application
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initialising flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)

    # Regestering the main blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # Regestering the auth bluprint
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors,forms

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from . import main
from ..models import Group,Line,Comment
from .forms import LineForm,CommentForm,GroupForm
from flask_login import login_required,current_user

@main.route('/')
def index():

    title = 'Home'

    groups = Group.get_groups()

    return render_template('index.html', title = title, groups=groups )

@main.route('/group/new', methods=['GET','POST'])
@login_required
def new_group():

    '''
    View new group route function that returns a page with a form to create a category
    '''

    form = GroupForm()

    if form.validate_on_submit():
        name = form.name.data
        new_group = Group(name=name)
        new_group.save_group()

        return redirect(url_for('.index'))

    title = 'New Group'
    return render_template('new-group.html', group_form = form)


@main.route('/group/<int:id>')
def group(id):

    '''
    View group route function that returns a list of pitches in the route and allows a user to create a pitch for the selected route
    '''
    group = Group.query.get(id)

    if group is None:
        abort(404)

    lines = Line.get_lines(id)
    title = f'{group.name} page'

    return render_template('group.html', title=title, group=group, lines=lines)

@main.route('/group/line/new/<int:id>', methods=['GET','POST'])
@login_required
def new_line(id):

    '''
    View new line route function that returns a page with a form to create a pitch for the specified category
    '''
    group = Group.query.filter_by(id=id).first()

    if group is None:
        abort(404)

    form = LineForm()

    if form.validate_on_submit():
        line_content = form.line_content.data
        new_line = Line( line_content=line_content, group=group, user=current_user)
        new_line.save_line()

        return redirect(url_for('.group', id=group.id ))

    title = 'New Pitch'
    return render_template('new_line.html', title=title, line_form=form)

@main.route('/line/<int:id>')
def single_line(id):

    '''
    View single line function that returns a page containing a pitch, its comments 
    '''
    line = Line.query.get(id)
    
    if line is None:
        abort(404)

    comments = Comment.get_comments(id)

    title = f'Pitch {line.id}'

    return render_template('line.html', title=title, line=line, comments=comments)

@main.route('/line/new/<int:id>', methods=['GET','POST'])
@login_required
def new_comment(id):

    '''
    View new line route function that returns a page with a form to create a pitch for the specified category
    '''
    line = Line.query.filter_by(id=id).first()

    if line is None:
        abort(404)

    form = CommentForm()

    if form.validate_on_submit():
        comment_content = form.comment_content.data
        new_comment = Comment( comment_content=comment_content, line=line, user=current_user)
        new_comment.save_comment()

        return redirect(url_for('.single_line', id=line.id ))

    title = 'New Comment'
    return render_template('new_comment.html', title=title, comment_form=form)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block -->
{% block navbar %}

    {% include 'navbar.html' %}
    
{% endblock %}

app/templates/group.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/group.css')}}">
    
    <link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
{% endblock %}

<!-- Content block -->
{% block content %}

    <title> {{ title }} </title>

    <div class="container">

        <div class="row">

            <div class="col-md-4 col-lg4">
    
                <h2 class="group-header">
                    List of {{group.name}}
                </h2>

            </div>

            <div class="col-md-4 col-lg4">
                
            </div>

            
            <div class="col-md-4 col-lg4">

                <h2 class="line-create">
                    <a href="/group/line/new/{{group.id}}">
                        Write A Pitch
                    </a>
                </h2>
                
            </div>

        </div>

        <hr>


        <ul class="list-unstyled">
            {{ macro.displayLineList(lines) }}
        </ul>


    </div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
    
    <link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
{% endblock %}

<!-- Content block -->
{% block content %}

    <title> {{ title }} </title>

    <div class="container">

        <div class="row">

            <div class="col-md-4 col-lg-4">

                <h2 class="category-header">
                    List of Categories
                </h2>
                
            </div>

            <div class="col-md-4 col-lg-4">
                
            </div>

            <div class="col-md-4 col-lg-4">
                <h2 class="category-create">
                    <a href="/group/new">
                        Create Category
                    </a>
                </h2>
                
            </div>

        </div>

        <hr>

        
        <ul class="list-unstyled">
            {{ macro.displayGroupList(groups) }}
        </ul>




    </div>

{% endblock %}

app/templates/line.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}


<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/line.css')}}">
    
    <link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
{% endblock %}

<!-- Content block -->
{% block content %}
    <title> {{ title }} </title>
    <div class="container">

        <div class="row">

            <div class="col-md-2 col-lg-2">

                    <a href="/group/{{line.group.id}}">

                        <i class="glyphicon glyphicon-menu-left back-icon"></i>

                    </a>
                
            </div>

            <div class=" col-xs-10 col-sm-10 col-md-8 col-lg-8">
            
                <h2> 

                    <a href="/group/{{line.group.id}}" class="pitch-content">
                        
                        {{ line.line_content }} 

                    </a>

                    <br>

                    <small class="pitch-author"> by {{ line.user.username }} </small>

                </h2>

            </div>


        <hr>

        <div class="row">
            <div class="col-md-4 col-lg-4">

                <h2 class="comment-header">
                    List of Comments
                </h2>
                
            </div>

            <div class="col-md-4 col-lg-4">
                
            </div>

            <div class="col-md-4 col-lg-4">

                <h3 class="comment-create">
                    <a href="/line/new/{{line.id}}">
                        Add Comment
                    </a>
                </h3>
                
            </div>
        </div>

        <hr>

        <ul class="list-unstyled">
            {{ macro.displayCommentList(comments) }}
        </ul>


    </div>
{% endblock %}

app/templates/macros.html
{% macro displayGroupList(group_list) %}

    {% for group in group_list %}
        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 category">
            
                <li class="text-center">

                    <h3 class="category-name">

                        <a href="/group/{{group.id}}">
                            {{ group.name }}   
                        </a>
                        
                    </h3>

                </li>

            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>

    {% endfor %}

{% endmacro %}


{% macro displayLineList(line_list) %}


    {% for line in line_list %}
        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 line">
            
                <li class="text-center">

                    <h3>

                        <a href="{{url_for('main.single_line', id = line.id )}}" class="pitch-content">
                            {{ line.line_content }}
                        </a>

                        <br>

                        <small class="pitch-author"> by {{ line.user.username }} </small>
                        
                    </h3>

                </li>

            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>

    {% endfor %}

{% endmacro %}


{% macro displayCommentList(comment_list) %}


    {% for comment in comment_list %}
        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 well comment-well">
            
                <li>

                    <h4 class="comment-content">
                        
                        {{ comment.comment_content}}

                        <br>

                        <small class="comment-author"> by {{ comment.user.username }} </small>
                        
                    </h4>

                </li>

            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>

    {% endfor %}

{% endmacro %}

app/templates/navbar.html
{% extends 'base.html' %}

<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/navbar.css')}}">
    
    <link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
{% endblock %}

<!-- Navbar block -->
{% block navbar %}
    <div class="container">

        <div class="navbar navbar-inverse" role="navigation" >

            <div class="container-fluid">

                <div class="navbar-header">

                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">

                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>

                    </button>

                    <a href="/" class="navbar-brand">One Minute Pitch</a>

                </div>

                <div class="navbar-collapse collapse">

                    <ul class="nav navbar-nav">

                        <li>
                            <a href="/">Home</a>
                        </li>
                        
                    </ul>

                    <ul class="nav navbar-nav navbar-right">

                      {% if current_user.is_authenticated %}

                          <li> <h4 class="username"> {{current_user.username}} </h4> </li>

                          <li> <a href="{{url_for('auth.logout')}}">Sign out</a> </li>

                          {% else %}

                          <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                          
                      {%endif%}

                    </ul>

                </div>

            </div>

        </div>

    </div>
{% endblock %}

app/templates/new-group.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}


<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/new_group.css')}}">
    
    <link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
{% endblock %}

<!-- Content block -->
{% block content %}
    <title> {{ title }} </title>
    
    <div class="container">

        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-group">
            
                {{ wtf.quick_form(group_form) }}
                
            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>
    </div>
{% endblock %}

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}


<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/new_comment.css')}}">
    
    <link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
{% endblock %}

<!-- Content block -->
{% block content %}
    <title> {{ title }} </title>
    
    <div class="container">

        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-comment">
            
                {{ wtf.quick_form(comment_form) }}
                
            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>
    </div>
{% endblock %}

app/templates/new_line.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}


<!-- Styles block -->
{% block styles%}
    {{ super() }}
    <link rel="stylesheet" href="{{url_for('static',filename='css/new_line.css')}}">
    
    <link href="https://fonts.googleapis.com/css?family=Habibi" rel="stylesheet">
{% endblock %}

<!-- Content block -->
{% block content %}
    <title> {{ title }} </title>
    
    <div class="container">

        <div class="row">
            
            <div class="col-md-2 col-lg-2">
                
            </div>

            <div class=" col-xs-12 col-sm-12 col-md-8 col-lg-8 create-line">
            
                {{ wtf.quick_form(line_form) }}
                
            </div>

            <div class="col-md-2 col-lg-2">
                
            </div>

        </div>
    </div>
{% endblock %}